### ISSUE TITLE
acceptance "test_periodic_deferrer" is flaky

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#276]
See the error in https://travis-ci.org/github/peopledoc/procrastinate/jobs/706522770
This does not reproduce easily.

I'm not sure whether this is a real subtle bug in periodic tasks or a test problem. We should analyze this and take appropriate measures.

**Comment by ewjoachim** [comment]
Hmm, seems to fail more often than I imagined: https://travis-ci.org/github/peopledoc/procrastinate/jobs/708812176

**Comment by ewjoachim** [comment]
Much much more often https://travis-ci.org/github/peopledoc/procrastinate/jobs/708814572

**Comment by elemoine** [comment]
> Much much more often https://travis-ci.org/github/peopledoc/procrastinate/jobs/708814572

It passed here.

**Comment by ewjoachim** [comment]
Yeah, I retried this one. I expected that it would use a new ID but apparently it didn't.

**Comment by ewjoachim** [comment]
Ok, first reassuring bit: we're not launching the same cron job twice: we're skipping one. Now on to why.

**Comment by elemoine** [comment]
I think I understand what's going on.

In that test we have a periodic task that repeats every second (`cron="* * * * * *"`). This works if the periodic worker does wake up every second. But if the worker wakes up a bit later we miss an event, and we don't get what we expect in the test.

Let's consider this scenario:

* the worker starts executing at 1596802880.0627189 (epoch time)
* the timestamp for the first execution of the periodic task is 1596802880
* the worker wakes up at say 1596802881.0899189
* the timestamp for the second execution of the periodic task is 1596802881
* then, the worker wakes up at 1596802883.0100000 (it missed the second 1596802882)
* the timestamp for the third execution of the periodic task is 1596802883 (and the test fails, because 1596802882 was expected in place of 1596802883)

This issue might be amplified by the 0.5 second [MARGIN](https://github.com/peopledoc/procrastinate/blob/dce801709585f4f8f54676359672965e0f3a9880/procrastinate/periodic.py#L175) we apply for the wait time.

**Comment by ewjoachim** [comment]
I'm ready to bet that in our current test setup, 100% of the problem is:
- occurring between the first and the 2nd launch, and not for subsequent launches
- because of the MARGIN

**Comment by elemoine** [comment]
Yep, I think you're right. The problem may occur between the first and second launch, and not for subsequent launches.

I've looked at the code again, and I am wondering if the problem isn't related to the fact that we have two `now`'s in the periodic tasks code. We have that of `get_previous_tasks` and that of `get_next_tick`. And the problem will trigger when the `now`'s don't belong to the same second interval.

Let's take an example:

* `get_previous_tasks` executes, and its `now` is 1597848469.9906602, meaning that the periodic task with timestamp 1597848469 is deferred
* `get_next_tick` executes, and its `now` is 1597848470.0023084, meaning that the next periodic task to defer will be that with timestamp 1597848471!!

So one way to fix the problem might be to make `get_previous_tasks` and `get_next_tick` always use the same `now`. I'll give it a try…

**Comment by elemoine** [comment]
This is why I am thinking about and currently testing: https://github.com/peopledoc/procrastinate/commit/bec3fc1aeb768e8a21558128b6e9c7e0eddd5743.

**Comment by ewjoachim** [comment]
Yes, I had the same conclusion :raised_hands:
