### ISSUE TITLE
Task objects created by app.task may not have the expected attributes

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#394]
In one of our applications we have our own `task` decorator, which looks like this:

```py
def task(f, lock=None, pass_context=False):
    f.lock = lock
    f.pass_context = pass_context
    registry[f.__qualname__] = f
    return f
```

and that we use like this:

```py
@task(lock="mylock", pass_context=False)
def mytaskfunc(…):
    …
```

And we have a setup function that basically does this:

```py
def setup_tasks():
    app = procrastinate.App(…)
    for name, task in registry.items():
        wrapped = task_wrapper(name, task)
        app.task(name=name, pass_context=True)(wrapped)
```

We expect that the `procrastinate.tasks.Task` objects created by `app.task` always have their `pass_context` set to `True`. But that's not the case: if the function object wrapped by `app.task` has `pass_context` set to `False` then the corresponding `procrastinate.tasks.Task` object will have `pass_context` set to `False` as well.

This is because Procrastinate [uses](https://github.com/peopledoc/procrastinate/blob/de781491bf59c317f1b57af02fe6a64dabb05b03/procrastinate/app.py#L187) [`functools.update_wrapper`](https://docs.python.org/3/library/functools.html#functools.update_wrapper) with its default `updated` value, making the wrapper function be updated with all the attributes of the wrapped function.

Using `functools.update_wrapper(task, func, updated=())` should fix the problem.

**Comment by ewjoachim** [comment]
I think I have understood the problem, but I'm not really sure.

The problem is that we're both defining a `pass_context` attribute on the task object for procrastinate and on the function for your project, and that one shadows the other. Right ?

You're referring to a `task_wrapper` that hasn't been defined, is it the function defined above as `task` ?

I think I'm ok to update the `update_wrapper` call if you think this will not cause other problems down the line.

**Comment by elemoine** [comment]
Sorry for not responding earlier! Yes, your understanding is correct.
