### ISSUE TITLE
Question: Reusing Postgresql session in task function

### ISSUE THREAD

**Issue by kbakk** [peopledoc/procrastinate#410]
Hello,

First of all, thank you for making this project available to the world!

I am looking into implementing this in a project, where a web server would queue a task to be executed by the worker. 

When running the worker, will it be possible to access the DB session, from within the task? I need to load a config from the database, and also write some information about the request being processed. 

Will it be possible to access job details (`job_id` in particular) from within the task being executed as well? If the task will need to be manually restarted, being able to add more context in a table, with a reference to the `procrastinate_jobs` table, could be helpful with presenting it in a UI.

Thanks,
Kristoffer

**Comment by ewjoachim** [comment]
I think that what you are looking for is ["How to: Get more context for task execution"](https://procrastinate.readthedocs.io/en/stable/howto/context.html).

Upon recieving the [JobContext](https://procrastinate.readthedocs.io/en/stable/reference.html#procrastinate.JobContext) object, you'll be able to access the App which has the connector, which has the DB session. You'll also have all the Job details. I'm not sure I 100% understand everything you need, but if there's something you'd like to have, we can think about it. Otherwise, I invite you to close the ticket if it's all good to you.

**Comment by kbakk** [comment]
Hi @ewjoachim,

Thanks for getting back to me. That does sound like what I'm after!

Cheers!
