### ISSUE TITLE
Add way to store data returned from task

### ISSUE THREAD

**Issue by tomdottom** [peopledoc/procrastinate#419]
For example when a job created from a task such as:

```shell
@app.task(pass_context=True)
async def hello_world(ctx):
    return "Hello World"
```

finishes successfully, then  the "Hello World" should be able to be looked up using the job id.

**Comment by ewjoachim** [comment]
As of today, the task result is logged, but not saved because this would mean the cleaning of finished tasks, which up until now was just a matter of maintenance, would become a matter of functionality too (you mustn't delete a finished task until its result was read, otherwise it's lost)

Your tasks are expected to have a side effect. But if your project, it's perfectly ok to define your own decorator that will store tasks results (and subsequently take care of the deletion) on your terms.

It might be interesting to expose a simpler way to define a "middleware" though.

**Comment by tomdottom** [comment]
Thanks for the explanation @ewjoachim 

I'll look at righting some decorators for storing returned values into a custom table.

**Comment by ewjoachim** [comment]
We might do something more straightforward, but until then: https://procrastinate.readthedocs.io/en/stable/howto/middleware.html

**Comment by ewjoachim** [comment]
Cf #370 : maybe we could revisit this decision some day. It may depend on whether there are volunteers who want to take a shot at implementing this.

**Comment by tomdottom** [comment]
@ewjoachim I quite like the idea of a decorator/middleware and associated helper to retrieve results. So maybe a simple API like:

```
@app.task
@store_result
async def hello_world():
    return "Hello World!"

...
   
with app.open():
    result = await fetch_result(await hello_world.defer_async())
```

I'm guessing a task should fail if storage fails, but am not 100% sure about this.

**Comment by ewjoachim** [comment]
> I quite like the idea of a decorator/middleware and associated helper to retrieve results

Do you mean you'd like Procrastinate to implement such a decorator, or doyou like the idea of being able to do this on your own in your app outside of the scope of procrastinate itself ?

> I'm guessing a task should fail if storage fails, but am not 100% sure about this.

I guess this is application-dependent :) Because storage specifics can be very custom. I think that's partly why I'm divided regarding having Procrastinate do this by itself.

**Comment by canadaduane** [comment]
Just wanted to add that I misunderstood what Procrastinate can/can't do and after implementing Procrastinate in my app, I'm probably rolling back to (pre-existing) celery implementation with [trunk](https://pypi.org/project/trunk/) due to its ability to wait until the task completes and then yield the result back to the caller.

In our case, we don't want jobs just "logging" that they finish, but, rather providing an ID back that tells us where to go to get the result of that particular job.

**Comment by ewjoachim** [comment]
Ok, sorry to see you go. If we end up steering toward this direction, I'll make sure to drop you a line :)

**Comment by canadaduane** [comment]
Thanks!
