### ISSUE TITLE
Declare tasks independently of an App

### ISSUE THREAD

**Issue by tomdottom** [peopledoc/procrastinate#421]
Currently the API allows up to define tasks with:

`/src/app.py`
```python
import procrastinate

task_app = procrastinate.App(
    connector=procrastinate.AiopgConnector()
    import_paths=[
        "tasks"
    ],
)
```

`/src/tasks.py`
```python
from app import task_app

@task_app.task()
def my_task():
    ...
```

But it might useful to make task definitions independent of the task_app
instance:

`/src/app.py`
```python
import procrastinate

task_app = procrastinate.App(
    connector=procrastinate.AiopgConnector()
    import_paths=[
        "tasks"
    ],
)
```

`/src/tasks.py`
```python
from procrastinate import task

# Then define tasks
@task()
def my_task():
    ...

```

This would allow task definitions to be moved and maintained in seperate
installable packages and configured like:

`/src/app.py`
```python
import procrastinate

task_app = procrastinate.App(
    connector=procrastinate.AiopgConnector()
    import_paths=[
        "other_package.procrastinate_tasks"
    ],
)
```

**Comment by ewjoachim** [comment]
The reason we need to link tasks to an app is that when a worker receives a task, it needs to know where to look for tasks. The design decision we did at the time is to keep a registry of known tasks in the app.

If we decided not to attach the registry to the app, the main other solution would be to put it as a global variable in the procrastinate package, which would allow having the API you mentionned. But this would also come with its own drawback: there could only be one procrsatinate app in memory. If we did that, the whole idea of creating an app would be moot: we would configure everything in procrastinate itself.

I think a better way of doing that would be to rely on tasks being explicitely loaded into procrastinate, and not being implicitly loaded when as a side-effect of importing the library:
```python
# external_library.py
import procrastinate

def mytask():
	...

def load_tasks(app: procrastinate.App):
	app.task(mytask)

# your_project.py
import procrastinate
import external_library

task_app = procrastinate.App(
    connector=procrastinate.AiopgConnector()
    import_paths=[
        "other_package.procrastinate_tasks"
    ],
)

external_library.load_tasks(task_app)

```
This is what we do for the builtin tasks, except that because we know which function to call, procrastinate does it by itself, but it really is the same thing:

https://github.com/peopledoc/procrastinate/blob/861553064218d33310b7fbdd198f0d43227de434/procrastinate/app.py#L104
https://github.com/peopledoc/procrastinate/blob/861553064218d33310b7fbdd198f0d43227de434/procrastinate/builtin_tasks.py#L35

You can even do the fancier version of it, which lets you define multiple tasks without having to list them in `load_task`, and which lets you call some task with specific task parameters:
```python

# external_library.py

tasks = []

def task(**kwargs):
	def wrap(func):
		tasks.append((func, kwargs))
	return wrap

@task(use_context=True)
def mytask(context: procrastinate.JobContext):
	...

def load_tasks(app: procrastinate.App):
	for task, kwargs in tasks:
		app.task(**kwargs)(task)

```

*That being said,*

There is such a thing as `setuptools` entrypoint, which lets any package define a callable and register it under a specific agreed-upon namespace. It would absolutely not be hard to make procrastinate, upon creation of an app, iterate on all registered entrypoint, and call the callable with the app.

That would make kind of the same code, except that `your_project.py` would not have to call `external_library.load_tasks(task_app)` and in `external_library`, the `setup.cfg` file (or `setup.py or pyproject.toml or ...) would define:
```ini
[options.entry_points]
raincoat.match =
	procrastinate.on_create_app = external_library:load_tasks
```

**Comment by tomdottom** [comment]
Thnx for that explanation @ewjoachim.

A simple task factory will definitely suffice for my needs and feels very similar to flask/starlette app factory patterns.
If I have the time I may create a documentation PR as the following pattern could be useful or others.

That said, it feels like we're only a small step away from Flask's Blueprints and Starlette's Mount patterns:

`external_library/tasks.py`
```python
from procrastinate import Blueprint
app = Blueprint()

@app.task
def my_task():
    ...
```

`scr/app.py`
```python
import procrastinate
import external_library.tasks as ext_tasks

task_app = procrastinate.App(
    connector=procrastinate.AiopgConnector()
)
task_app.register_tasks(ext_tasks.app)
```

As for automagical mounting of tasks using setuptools or other plugin systems, I think I'll leave that for now as I generaly prefer:

```shell
$ python -m this
The Zen of Python, by Tim Peters
...
Explicit is better than implicit.
Simple is better than complex.
...
```

**Comment by ewjoachim** [comment]
Blueprints seems awesome!

Do you want to submit a PR for that?

**Comment by tomdottom** [comment]
@ewjoachim please see #421
