### ISSUE TITLE
Capture logs for individual jobs

### ISSUE THREAD

**Issue by tomdottom** [peopledoc/procrastinate#431]
It should be possible to easily inspect logs of a single job that has run.

# Option 1

Update the logger formatting to include the task name & id so that backend logs can be easily filtered.

# Option 2

- Dynamically create new logging handlers & filters when a job is run to collect logs only for the job.
- Save these in a new table associated with the job.
- Provide a way to access logs from job instances

```python
job = app.job_manager.list_job(id=1)
for attempt in jobs.attempts:
    print(attempt.logs)
```

```sql
CREATE TABLE procrastinate_logs (
    id BIGSERIAL PRIMARY KEY,
    job_id integer NOT NULL REFERENCES procrastinate_jobs ON DELETE CASCADE,
    attempt_id integer NOT NULL,
    logs TEXT,
);
```

**Comment by ewjoachim** [comment]
I'm not fond of option 2.

Regarding option 1, I'm surprised it's not already the case.

Here are the JSON logs from the demo application:
```
{"message": "Starting worker on all queues", "action": "start_worker", "worker": {"name": "worker", "id": null, "queues": null}, "queues": null}

{"message": "Periodic task procrastinate_demo.tasks.tick deferred for timestamp 1627913136 with id 54659", "action": "periodic_task_deferred", "task": "procrastinate_demo.tasks.tick", "timestamp": 1627913136, "job_id": 54659}

{"message": "Starting job procrastinate_demo.tasks.tick[54659](timestamp=1627913136)", "action": "start_job", "worker": {"name": "worker", "id": 0, "queues": null}, "job": {"id": 54659, "status": "doing", "queue": "default", "lock": null, "queueing_lock": null, "task_name": "procrastinate_demo.tasks.tick", "task_kwargs": {"timestamp": 1627913136}, "scheduled_at": null, "attempts": 0, "call_string": "procrastinate_demo.tasks.tick[54659](timestamp=1627913136)"}, "start_timestamp": 1627913136.5743792, "duration": 1.8835067749023438e-05}

{"message": "Job procrastinate_demo.tasks.tick[54659](timestamp=1627913136) ended with status: Success, lasted 0.000 s - Result: 1627913136", "action": "job_success", "worker": {"name": "worker", "id": 0, "queues": null}, "job": {"id": 54659, "status": "doing", "queue": "default", "lock": null, "queueing_lock": null, "task_name": "procrastinate_demo.tasks.tick", "task_kwargs": {"timestamp": 1627913136}, "scheduled_at": null, "attempts": 0, "call_string": "procrastinate_demo.tasks.tick[54659](timestamp=1627913136)"}, "start_timestamp": 1627913136.5743792, "duration": 0.0001957416534423828, "end_timestamp": 1627913136.574575, "result": 1627913136}

```
In the first message, there's not task.

In the 2nd one I see: `"task": "procrastinate_demo.tasks.tick"` and `"job_id": 54659`

In the 3rd and 4th message: `"task_name": "procrastinate_demo.tasks.tick"` and `"id": 54659`. I agree that the inconsistency is sad, and I believe we can do something about it. But as far as I can tell, what you're asking for is already there, no?

**Comment by ewjoachim** [comment]
Aaaah you're talking about the default formatter. I guess that in real applications, they're using a more advanced formatter, such as JSON (that what we do in our applications).
We could set a default formatter that outputs more than the Python default, but I'm not sure it's worth adding a dependency for this, especially since it will probably not be used in most real cases.

What would you have in mind for the format, if not JSON ?

**Comment by tomdottom** [comment]
So, inspecting my logs I do now see that the general format of the logs is:
```
INFO:procrastinate.jobs:Deferred job fully.qualified.task_name[<<task_id>>](<<task args>>)
```

which is indeed enough for filtering logs for a job.  Apologies for not noticing this before.

I am running into the classic problem where the exec_info traceback is emitted over multiple lines, but I guess this is really a logging setup issue.  Worst case scenario I can just copy/paste https://docs.python.org/3.5/howto/logging-cookbook.html#customized-exception-formatting

**Comment by tomdottom** [comment]
With respect to

> I'm not fond of option 2.

what problems does your _spidey sense_ foresee?

Or is it more of an issue that it doesn't fit into the current philosophical framework of Procrastinate?

**Comment by ewjoachim** [comment]
> what problems does your spidey sense foresee?

For me the logs are a monitoring / functional matter, and what we have in the DB is functional, it's linked to procrastinate working. People may have wild expectations of things to do with logs, including sending them to a different machine, to a log collector (datadog, ELK, ...), etc. The Python `logging` standard library is extremely customizable for this exact reason. You could even define your own handler that stores the log in your DB if you want, but that really is a personal choice.

Our responsibility, on the other hand, is to provide logs with as much structure as possible, which we do by attaching a lot of context information to each and every log we emit (see the json logs I pasted above).

By default, the formatter only shows quite basic information on our logs, but that just because Python's basic formatter is, as said, basic. A better formatter (see https://github.com/madzak/python-json-logger for example) would display every bit of information that the logs have, and in a structured way, allowing any structured-logging friendly application to make the most out of it.

Also, we do indeed display `task_name[<<task_id>>](<<task args>>)` in the text message of the log as to make it barely usable for people not using a better formatter, but that still put the logs at a fraction of how useful they can be with proper structure (a.k.a JSON).

Have you seen https://procrastinate.readthedocs.io/en/stable/howto/logging.html?highlight=log#make-the-most-out-of-the-logging-system ?

**Comment by tomdottom** [comment]
I had indeed stumbled upon [How to make the most out of the logging system](https://procrastinate.readthedocs.io/en/stable/howto/logging.html?highlight=log#make-the-most-out-of-the-logging-system), but thanks for the link.

I guess I have a use case which is outside of the core of Procrastinate.

I have hacked together a small UI web lists all the jobs and their info.  Option 2 is really there to support the fact that I want to easily inspect the logs of a failed job, and if the cause of the error is an upstream failure simply restart/reschedule the job.

If this is deemed to be outside of the core of Procrastinate that's perfectly fine and I'll happily close this issue.

I'm pretty sure we can add a custom table and write a task decorator to capture and store the logs.
It might be nice to have some hooks so that I could setup/teardown logging before `process_job`/`run_job` is called as to capture the logging within these methods, but this is not a major issue.

Just in case you are interested here's my [gist showing how to collect logs for separate async jobs](https://gist.github.com/tomdottom/50886f5216ac5875b06b923a50df59d1)

**Comment by ewjoachim** [comment]
Nice code !

I believe you don't have to attach a new handler for every task, and remove it afterwards. Your approach of using a QueueHandler is spot on for separation of concerns. You could have a single queue handler. On the queue consumer side, you would store logs based on the job id, and when you receive a `finish_task` log, you know it's over. (Additionally, if you're afraid of missing a task end, you could always track the worker id and check whenever the same worker_id is associated to a different job id.

The only thing is where you would store the tasks, and I believe it's perfectly appropriate to store them in the same database as procrastinate (even re-use the connection if you want), but I'm still unsure about Procrastinate doing it itself, this really seems like a specific usecase.

Let's say that as long as we don't store task results, I'm not comfortable storing logs :)

**Comment by tomdottom** [comment]
> ... but I'm still unsure about Procrastinate doing it itself, this really seems like a specific usecase.
>
> Let's say that as long as we don't store task results, I'm not comfortable storing logs :)

I actually see a reasonable difference between job results and job logs.

In an other thread you had mentioned that you were wary of storing job results as these would be deleted when old jobs were cleaned up.  I completely see your point on this, after all you could end up in a situation where users are not cleaning up old jobs because they are relying on data stored in the job results.

However, I don't see why we would worry about deleting an old job's logs along with the old job itself.  The stored logs would just be a text blob that is unlikely to be queried and relied upon, and only really looked at to quickly diagnose a failing job (at least this is what I used job logs for when fighting with AirFlow).

You can still be wary of storing logs, but it'll have to be for it's own unique reason :wink:

**Comment by ewjoachim** [comment]
You drive a hard bargain 😄 

On your side, I guess you do realize that you could totally be providing a `ProcrastinatePostgresLogStorageHandler` class in another codebase, which could also be open source 😄 ? Ok, you'd have to redo a bit of boilerplate...

If you want a real reason, I'm afraid that this could add some complexity to the future developments, because we'd need to support this feature in the foreseeable future (& non negligeable storage size requirements for users. Imagine if each task produced 1GB of logs?)

(Hey, I see you're invested and persistent in helping this library grow. Would you be interested in an official position in the maintenance team at some point? Maybe not right now, but that's definitely something I'd love to work out with you if you're interested. Feel free to contact me on twitter or at first name @ last name . fr if you want to discuss that privately.)

**Comment by tomdottom** [comment]
> Imagine if each task produced 1GB of logs?

Good point, the logs should definitely be gzipped at rest :wink:

But I take your point that you could be storing a lot of data in the db, when Procrastinate itself would be very lightweight.

> this could add some complexity to the future developments

Do you have a roadmap?

**Comment by tomdottom** [comment]
I'm closing this in favour of a separate `ProcrastinatePostgresLogStorageHandler` (or possibly something with a shorter name).

**Comment by ewjoachim** [comment]
> Do you have a roadmap?

Not really at the point. I never found myself in an position that I'd need a roadmap for an opensource project. The roadmap is "eventually, let's tackle all the issues" :D
